---
parameters:
  composeFile:

steps:
    - task: DockerCompose@0
      displayName: Start containers from ${{ parameters.composeFile }}
      inputs:
          containerregistrytype: "Container Registry"
          dockerComposeFile: ${{ parameters.composeFile }}
          dockerComposeFileArgs: "DB_PASSWORD=$(DB_PASSWORD)"
          action: "Run services"
