---
steps:
    - task: PowerShell@2
      displayName: Install RabbitMQ
      inputs:
          targetType: "inline"
          script: choco install rabbitmq
    - template: ./wait-for.tmpl.yml
      parameters:
          name: RabbitMQ
          cmd: rabbitmq-diagnostics -q ping
