
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.10.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Setup {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.TextField tbDefaultYaml;
        
        private Terminal.Gui.Button btnBrowseForDefaultYaml;
        
        private Terminal.Gui.CheckBox cbYamlValid;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Button btnCheckInfrastructure;
        
        private Terminal.Gui.LineView lineview1;
        
        private Terminal.Gui.CheckBox cbRabbitMq;
        
        private Terminal.Gui.Button btnTryRabbitMq;
        
        private Terminal.Gui.CheckBox cbMongoDb;
        
        private Terminal.Gui.Button btnTryMongoDb;
        
        private Terminal.Gui.CheckBox cbRdmp;
        
        private Terminal.Gui.Button btnTryRdmp;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.Button btnCheckMicroservices;
        
        private Terminal.Gui.LineView lineview2;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Label label42;
        
        private Terminal.Gui.CheckBox cbDicomTagReader;
        
        private Terminal.Gui.CheckBox cbCohortExtractor;
        
        private Terminal.Gui.CheckBox cbMongoDbPopulator;
        
        private Terminal.Gui.CheckBox cbDicomAnonymiser;
        
        private Terminal.Gui.CheckBox cbIdentifierMapper;
        
        private Terminal.Gui.CheckBox cbIsIdentifiable;
        
        private Terminal.Gui.CheckBox cbDicomRelationalMapper;
        
        private Terminal.Gui.CheckBox cbCohortPackager;
        
        private void InitializeComponent() {
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Setup Tester (Ctrl+Q to exit)";
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 12;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "Config File:";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.tbDefaultYaml = new Terminal.Gui.TextField();
            this.tbDefaultYaml.Width = Dim.Fill(15);
            this.tbDefaultYaml.Height = 1;
            this.tbDefaultYaml.X = 13;
            this.tbDefaultYaml.Y = 0;
            this.tbDefaultYaml.Secret = false;
            this.tbDefaultYaml.Data = "tbDefaultYaml";
            this.tbDefaultYaml.Text = "";
            this.tbDefaultYaml.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbDefaultYaml);
            this.btnBrowseForDefaultYaml = new Terminal.Gui.Button();
            this.btnBrowseForDefaultYaml.Width = 13;
            this.btnBrowseForDefaultYaml.Height = 1;
            this.btnBrowseForDefaultYaml.X = Pos.Right(tbDefaultYaml) + 1;
            this.btnBrowseForDefaultYaml.Y = 0;
            this.btnBrowseForDefaultYaml.Data = "btnBrowseForDefaultYaml";
            this.btnBrowseForDefaultYaml.Text = "Browse...";
            this.btnBrowseForDefaultYaml.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnBrowseForDefaultYaml.IsDefault = false;
            this.Add(this.btnBrowseForDefaultYaml);
            this.cbYamlValid = new Terminal.Gui.CheckBox();
            this.cbYamlValid.Width = 1;
            this.cbYamlValid.Height = 1;
            this.cbYamlValid.X = Pos.Left(tbDefaultYaml);
            this.cbYamlValid.Y = 1;
            this.cbYamlValid.Data = "cbYamlValid";
            this.cbYamlValid.Text = "Yaml Valid";
            this.cbYamlValid.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbYamlValid.Checked = false;
            this.Add(this.cbYamlValid);
            this.label2 = new Terminal.Gui.Label();
            this.label2.Width = 15;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 2;
            this.label2.Data = "label2";
            this.label2.Text = "Infrastructure";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.btnCheckInfrastructure = new Terminal.Gui.Button();
            this.btnCheckInfrastructure.Width = 9;
            this.btnCheckInfrastructure.Height = 1;
            this.btnCheckInfrastructure.X = 15;
            this.btnCheckInfrastructure.Y = 2;
            this.btnCheckInfrastructure.Data = "btnCheckInfrastructure";
            this.btnCheckInfrastructure.Text = "Check";
            this.btnCheckInfrastructure.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCheckInfrastructure.IsDefault = false;
            this.Add(this.btnCheckInfrastructure);
            this.lineview1 = new Terminal.Gui.LineView();
            this.lineview1.Width = Dim.Fill(0);
            this.lineview1.Height = 1;
            this.lineview1.X = 0;
            this.lineview1.Y = 3;
            this.lineview1.Data = "lineview1";
            this.lineview1.Text = "";
            this.lineview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lineview1.LineRune = '─';
            this.lineview1.Orientation = Terminal.Gui.Graphs.Orientation.Horizontal;
            this.Add(this.lineview1);
            this.cbRabbitMq = new Terminal.Gui.CheckBox();
            this.cbRabbitMq.Width = 4;
            this.cbRabbitMq.Height = 1;
            this.cbRabbitMq.X = 2;
            this.cbRabbitMq.Y = 4;
            this.cbRabbitMq.Data = "cbRabbitMq";
            this.cbRabbitMq.Text = "RabbitMq";
            this.cbRabbitMq.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbRabbitMq.Checked = true;
            this.Add(this.cbRabbitMq);
            this.btnTryRabbitMq = new Terminal.Gui.Button();
            this.btnTryRabbitMq.Width = 7;
            this.btnTryRabbitMq.Height = 1;
            this.btnTryRabbitMq.X = 25;
            this.btnTryRabbitMq.Y = 4;
            this.btnTryRabbitMq.Data = "btnTryRabbitMq";
            this.btnTryRabbitMq.Text = "Try";
            this.btnTryRabbitMq.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryRabbitMq.IsDefault = false;
            this.Add(this.btnTryRabbitMq);
            this.cbMongoDb = new Terminal.Gui.CheckBox();
            this.cbMongoDb.Width = 4;
            this.cbMongoDb.Height = 1;
            this.cbMongoDb.X = 2;
            this.cbMongoDb.Y = 5;
            this.cbMongoDb.Data = "cbMongoDb";
            this.cbMongoDb.Text = "MongoDb";
            this.cbMongoDb.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbMongoDb.Checked = false;
            this.Add(this.cbMongoDb);
            this.btnTryMongoDb = new Terminal.Gui.Button();
            this.btnTryMongoDb.Width = 7;
            this.btnTryMongoDb.Height = 1;
            this.btnTryMongoDb.X = 25;
            this.btnTryMongoDb.Y = 5;
            this.btnTryMongoDb.Data = "btnTryMongoDb";
            this.btnTryMongoDb.Text = "Try";
            this.btnTryMongoDb.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryMongoDb.IsDefault = false;
            this.Add(this.btnTryMongoDb);
            this.cbRdmp = new Terminal.Gui.CheckBox();
            this.cbRdmp.Width = 4;
            this.cbRdmp.Height = 1;
            this.cbRdmp.X = 2;
            this.cbRdmp.Y = 6;
            this.cbRdmp.Data = "cbRdmp";
            this.cbRdmp.Text = "RDMP";
            this.cbRdmp.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbRdmp.Checked = true;
            this.Add(this.cbRdmp);
            this.btnTryRdmp = new Terminal.Gui.Button();
            this.btnTryRdmp.Width = 7;
            this.btnTryRdmp.Height = 1;
            this.btnTryRdmp.X = 25;
            this.btnTryRdmp.Y = 6;
            this.btnTryRdmp.Data = "btnTryRdmp";
            this.btnTryRdmp.Text = "Try";
            this.btnTryRdmp.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryRdmp.IsDefault = false;
            this.Add(this.btnTryRdmp);
            this.label3 = new Terminal.Gui.Label();
            this.label3.Width = 14;
            this.label3.Height = 1;
            this.label3.X = 0;
            this.label3.Y = 8;
            this.label3.Data = "label3";
            this.label3.Text = "Microservices";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.btnCheckMicroservices = new Terminal.Gui.Button();
            this.btnCheckMicroservices.Width = 9;
            this.btnCheckMicroservices.Height = 1;
            this.btnCheckMicroservices.X = 14;
            this.btnCheckMicroservices.Y = 8;
            this.btnCheckMicroservices.Data = "btnCheckMicroservices";
            this.btnCheckMicroservices.Text = "Check";
            this.btnCheckMicroservices.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCheckMicroservices.IsDefault = false;
            this.Add(this.btnCheckMicroservices);
            this.lineview2 = new Terminal.Gui.LineView();
            this.lineview2.Width = Dim.Fill(0);
            this.lineview2.Height = 1;
            this.lineview2.X = 0;
            this.lineview2.Y = 9;
            this.lineview2.Data = "lineview2";
            this.lineview2.Text = "";
            this.lineview2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lineview2.LineRune = '─';
            this.lineview2.Orientation = Terminal.Gui.Graphs.Orientation.Horizontal;
            this.Add(this.lineview2);
            this.label4 = new Terminal.Gui.Label();
            this.label4.Width = 9;
            this.label4.Height = 1;
            this.label4.X = 0;
            this.label4.Y = 10;
            this.label4.Data = "label4";
            this.label4.Text = "Data Load";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.label42 = new Terminal.Gui.Label();
            this.label42.Width = 10;
            this.label42.Height = 1;
            this.label42.X = 27;
            this.label42.Y = 10;
            this.label42.Data = "label42";
            this.label42.Text = "Extraction";
            this.label42.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label42);
            this.cbDicomTagReader = new Terminal.Gui.CheckBox();
            this.cbDicomTagReader.Width = 4;
            this.cbDicomTagReader.Height = 1;
            this.cbDicomTagReader.X = 1;
            this.cbDicomTagReader.Y = 11;
            this.cbDicomTagReader.Data = "cbDicomTagReader";
            this.cbDicomTagReader.Text = "DicomTagReader";
            this.cbDicomTagReader.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbDicomTagReader.Checked = false;
            this.Add(this.cbDicomTagReader);
            this.cbCohortExtractor = new Terminal.Gui.CheckBox();
            this.cbCohortExtractor.Width = 4;
            this.cbCohortExtractor.Height = 1;
            this.cbCohortExtractor.X = 28;
            this.cbCohortExtractor.Y = 11;
            this.cbCohortExtractor.Data = "cbCohortExtractor";
            this.cbCohortExtractor.Text = "CohortExtractor";
            this.cbCohortExtractor.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbCohortExtractor.Checked = true;
            this.Add(this.cbCohortExtractor);
            this.cbMongoDbPopulator = new Terminal.Gui.CheckBox();
            this.cbMongoDbPopulator.Width = 4;
            this.cbMongoDbPopulator.Height = 1;
            this.cbMongoDbPopulator.X = 1;
            this.cbMongoDbPopulator.Y = 12;
            this.cbMongoDbPopulator.Data = "cbMongoDbPopulator";
            this.cbMongoDbPopulator.Text = "MongoDbPopulator";
            this.cbMongoDbPopulator.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbMongoDbPopulator.Checked = false;
            this.Add(this.cbMongoDbPopulator);
            this.cbDicomAnonymiser = new Terminal.Gui.CheckBox();
            this.cbDicomAnonymiser.Width = 4;
            this.cbDicomAnonymiser.Height = 1;
            this.cbDicomAnonymiser.X = 28;
            this.cbDicomAnonymiser.Y = 12;
            this.cbDicomAnonymiser.Data = "cbDicomAnonymiser";
            this.cbDicomAnonymiser.Text = "DicomAnonymiser";
            this.cbDicomAnonymiser.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbDicomAnonymiser.Checked = true;
            this.Add(this.cbDicomAnonymiser);
            this.cbIdentifierMapper = new Terminal.Gui.CheckBox();
            this.cbIdentifierMapper.Width = 4;
            this.cbIdentifierMapper.Height = 1;
            this.cbIdentifierMapper.X = 1;
            this.cbIdentifierMapper.Y = 13;
            this.cbIdentifierMapper.Data = "cbIdentifierMapper";
            this.cbIdentifierMapper.Text = "IdentifierMapper";
            this.cbIdentifierMapper.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbIdentifierMapper.Checked = true;
            this.Add(this.cbIdentifierMapper);
            this.cbIsIdentifiable = new Terminal.Gui.CheckBox();
            this.cbIsIdentifiable.Width = 4;
            this.cbIsIdentifiable.Height = 1;
            this.cbIsIdentifiable.X = 28;
            this.cbIsIdentifiable.Y = 13;
            this.cbIsIdentifiable.Data = "cbIsIdentifiable";
            this.cbIsIdentifiable.Text = "IsIdentifiable";
            this.cbIsIdentifiable.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbIsIdentifiable.Checked = false;
            this.Add(this.cbIsIdentifiable);
            this.cbDicomRelationalMapper = new Terminal.Gui.CheckBox();
            this.cbDicomRelationalMapper.Width = 4;
            this.cbDicomRelationalMapper.Height = 1;
            this.cbDicomRelationalMapper.X = 1;
            this.cbDicomRelationalMapper.Y = 14;
            this.cbDicomRelationalMapper.Data = "cbDicomRelationalMapper";
            this.cbDicomRelationalMapper.Text = "DicomRelationalMapper";
            this.cbDicomRelationalMapper.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbDicomRelationalMapper.Checked = true;
            this.Add(this.cbDicomRelationalMapper);
            this.cbCohortPackager = new Terminal.Gui.CheckBox();
            this.cbCohortPackager.Width = 4;
            this.cbCohortPackager.Height = 1;
            this.cbCohortPackager.X = 28;
            this.cbCohortPackager.Y = 14;
            this.cbCohortPackager.Data = "cbCohortPackager";
            this.cbCohortPackager.Text = "CohortPackager";
            this.cbCohortPackager.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbCohortPackager.Checked = false;
            this.Add(this.cbCohortPackager);
        }
    }
}
