---
version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-YourStrongPassw0rd}
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrongPassw0rd}
    ports:
      - 1433:1433
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command:
      - bash
      - -c
      - |
        set -e
        mongod --bind_ip_all --fork --logpath /var/log/mongodb.log --replSet rs0
        if ! mongosh --quiet --eval "rs.status()" >/dev/null 2>&1; then
          mongosh --eval "rs.initiate()"
        else
          echo "Replica set already initialized."
        fi
        tail -f /dev/null
    ports:
      - 27017:27017
    restart: always
