---
version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-YourStrongPassw0rd}
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrongPassw0rd}
    ports:
      - 1433:1433
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: mongod --replSet rs0
    ports:
      - 27017:27017
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
