
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.10.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Setup {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.TextField tbDefaultYaml;
        
        private Terminal.Gui.Button btnBrowseForDefaultYaml;
        
        private Terminal.Gui.Button btnRefreshInfrastructure;
        
        private Terminal.Gui.CheckBox cbYamlValid;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.LineView lineview1;
        
        private Terminal.Gui.CheckBox cbRabbitMq;
        
        private Terminal.Gui.Button btnTryRabbitMq;
        
        private Terminal.Gui.CheckBox cbMongoDb;
        
        private Terminal.Gui.Button btnTryMongoDb;
        
        private Terminal.Gui.CheckBox cbRelationalDatabase;
        
        private Terminal.Gui.Button btnTryRelationalDb;
        
        private Terminal.Gui.CheckBox cbRdmp;
        
        private Terminal.Gui.Button btnTryRdmp;
        
        private void InitializeComponent() {
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = null;
            this.label1 = new Terminal.Gui.Label();
            this.label1.Width = 12;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.label1.Data = "label1";
            this.label1.Text = "Config File:";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.tbDefaultYaml = new Terminal.Gui.TextField();
            this.tbDefaultYaml.Width = Dim.Fill(15);
            this.tbDefaultYaml.Height = 1;
            this.tbDefaultYaml.X = 13;
            this.tbDefaultYaml.Y = 0;
            this.tbDefaultYaml.Secret = false;
            this.tbDefaultYaml.Data = "tbDefaultYaml";
            this.tbDefaultYaml.Text = "";
            this.tbDefaultYaml.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tbDefaultYaml);
            this.btnBrowseForDefaultYaml = new Terminal.Gui.Button();
            this.btnBrowseForDefaultYaml.Width = 13;
            this.btnBrowseForDefaultYaml.Height = 1;
            this.btnBrowseForDefaultYaml.X = Pos.Right(tbDefaultYaml) + 1;
            this.btnBrowseForDefaultYaml.Y = 0;
            this.btnBrowseForDefaultYaml.Data = "btnBrowseForDefaultYaml";
            this.btnBrowseForDefaultYaml.Text = "Browse...";
            this.btnBrowseForDefaultYaml.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnBrowseForDefaultYaml.IsDefault = false;
            this.Add(this.btnBrowseForDefaultYaml);
            this.btnRefreshInfrastructure = new Terminal.Gui.Button();
            this.btnRefreshInfrastructure.Width = 11;
            this.btnRefreshInfrastructure.Height = 1;
            this.btnRefreshInfrastructure.X = 13;
            this.btnRefreshInfrastructure.Y = 1;
            this.btnRefreshInfrastructure.Data = "btnRefreshInfrastructure";
            this.btnRefreshInfrastructure.Text = "Refresh";
            this.btnRefreshInfrastructure.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnRefreshInfrastructure.IsDefault = false;
            this.Add(this.btnRefreshInfrastructure);
            this.cbYamlValid = new Terminal.Gui.CheckBox();
            this.cbYamlValid.Width = 4;
            this.cbYamlValid.Height = 1;
            this.cbYamlValid.X = 26;
            this.cbYamlValid.Y = 1;
            this.cbYamlValid.Data = "cbYamlValid";
            this.cbYamlValid.Text = "Yaml Valid";
            this.cbYamlValid.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbYamlValid.Checked = true;
            this.Add(this.cbYamlValid);
            this.label2 = new Terminal.Gui.Label();
            this.label2.Width = 15;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 2;
            this.label2.Data = "label2";
            this.label2.Text = "Infrastructure:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.lineview1 = new Terminal.Gui.LineView();
            this.lineview1.Width = Dim.Fill(0);
            this.lineview1.Height = 1;
            this.lineview1.X = 0;
            this.lineview1.Y = 3;
            this.lineview1.Data = "lineview1";
            this.lineview1.Text = "";
            this.lineview1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lineview1.LineRune = '─';
            this.lineview1.Orientation = Terminal.Gui.Graphs.Orientation.Horizontal;
            this.Add(this.lineview1);
            this.cbRabbitMq = new Terminal.Gui.CheckBox();
            this.cbRabbitMq.Width = 4;
            this.cbRabbitMq.Height = 1;
            this.cbRabbitMq.X = 2;
            this.cbRabbitMq.Y = 4;
            this.cbRabbitMq.Data = "cbRabbitMq";
            this.cbRabbitMq.Text = "RabbitMq";
            this.cbRabbitMq.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbRabbitMq.Checked = true;
            this.Add(this.cbRabbitMq);
            this.btnTryRabbitMq = new Terminal.Gui.Button();
            this.btnTryRabbitMq.Width = 7;
            this.btnTryRabbitMq.Height = 1;
            this.btnTryRabbitMq.X = 25;
            this.btnTryRabbitMq.Y = 4;
            this.btnTryRabbitMq.Data = "btnTryRabbitMq";
            this.btnTryRabbitMq.Text = "Try";
            this.btnTryRabbitMq.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryRabbitMq.IsDefault = false;
            this.Add(this.btnTryRabbitMq);
            this.cbMongoDb = new Terminal.Gui.CheckBox();
            this.cbMongoDb.Width = 4;
            this.cbMongoDb.Height = 1;
            this.cbMongoDb.X = 2;
            this.cbMongoDb.Y = 5;
            this.cbMongoDb.Data = "cbMongoDb";
            this.cbMongoDb.Text = "MongoDb";
            this.cbMongoDb.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbMongoDb.Checked = false;
            this.Add(this.cbMongoDb);
            this.btnTryMongoDb = new Terminal.Gui.Button();
            this.btnTryMongoDb.Width = 7;
            this.btnTryMongoDb.Height = 1;
            this.btnTryMongoDb.X = 25;
            this.btnTryMongoDb.Y = 5;
            this.btnTryMongoDb.Data = "btnTryMongoDb";
            this.btnTryMongoDb.Text = "Try";
            this.btnTryMongoDb.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryMongoDb.IsDefault = false;
            this.Add(this.btnTryMongoDb);
            this.cbRelationalDatabase = new Terminal.Gui.CheckBox();
            this.cbRelationalDatabase.Width = 4;
            this.cbRelationalDatabase.Height = 1;
            this.cbRelationalDatabase.X = 2;
            this.cbRelationalDatabase.Y = 6;
            this.cbRelationalDatabase.Data = "cbRelationalDatabase";
            this.cbRelationalDatabase.Text = "Relational Database";
            this.cbRelationalDatabase.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbRelationalDatabase.Checked = true;
            this.Add(this.cbRelationalDatabase);
            this.btnTryRelationalDb = new Terminal.Gui.Button();
            this.btnTryRelationalDb.Width = 7;
            this.btnTryRelationalDb.Height = 1;
            this.btnTryRelationalDb.X = 25;
            this.btnTryRelationalDb.Y = 6;
            this.btnTryRelationalDb.Data = "btnTryRelationalDb";
            this.btnTryRelationalDb.Text = "Try";
            this.btnTryRelationalDb.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryRelationalDb.IsDefault = false;
            this.Add(this.btnTryRelationalDb);
            this.cbRdmp = new Terminal.Gui.CheckBox();
            this.cbRdmp.Width = 4;
            this.cbRdmp.Height = 1;
            this.cbRdmp.X = 2;
            this.cbRdmp.Y = 7;
            this.cbRdmp.Data = "cbRdmp";
            this.cbRdmp.Text = "RDMP";
            this.cbRdmp.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cbRdmp.Checked = true;
            this.Add(this.cbRdmp);
            this.btnTryRdmp = new Terminal.Gui.Button();
            this.btnTryRdmp.Width = 7;
            this.btnTryRdmp.Height = 1;
            this.btnTryRdmp.X = 25;
            this.btnTryRdmp.Y = 7;
            this.btnTryRdmp.Data = "btnTryRdmp";
            this.btnTryRdmp.Text = "Try";
            this.btnTryRdmp.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTryRdmp.IsDefault = false;
            this.Add(this.btnTryRdmp);
        }
    }
}
