CREATE DATABASE IF NOT EXISTS smi; 

CREATE TABLE `smi`.`IO_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_IO_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`IO_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(16)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_IO_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`IO_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_IO_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`MG_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`PatientID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_MG_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`MG_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(255)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_MG_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`MG_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_MG_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`RF_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_RF_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`RF_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_RF_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`RF_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_RF_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`SR_ImageTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`CompletionFlag` varchar(16)    NULL , 
`VerificationFlag` varchar(16)    NULL , 
`StrainNomenclature` varchar(64)    NULL , 
`StrainDescription` text    NULL , 
`SOPClassUID` varchar(64)    NULL , 
`Study_ReferencedSOPClassUID` text    NULL , 
`Study_ReferencedSOPInstanceUID` text    NULL , 
`RefImageSeq_ReferencedSOPClassUID` text    NULL , 
`RefImageSeq_ReferencedSOPInstanceUID` text    NULL , 
`SourceImageSeq_ReferencedSOPClassUID` varchar(500)    NULL , 
`SourceImageSeq_ReferencedSOPInstanceUID` varchar(500)    NULL , 
`RefProcStep_ReferencedSOPClassUID` text    NULL , 
`RefProcStep_ReferencedSOPInstanceUID` text    NULL , 
`CurrentReqEvidence_StudyInstanceUID` text    NULL , 
`CurrentReqEvidence_SeriesInstanceUID` text    NULL , 
`CurrentReqEvidence_SOPClassUID` text    NULL , 
`CurrentReqEvidence_SOPInstanceUID` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
CONSTRAINT PK_SR_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`US_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_US_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`US_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_US_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`US_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_US_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`XA_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionTime` time    NULL , 
`AveragePulseWidth` decimal(38,19)    NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`ColorSpace` varchar(16)    NULL , 
`Columns` smallint    NULL , 
`DerivationDescription` text    NULL , 
`DetectorConfiguration` varchar(16)    NULL , 
`DetectorDescription` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorPrimaryAngle` decimal(38,19)    NULL , 
`DetectorSecondaryAngle` decimal(38,19)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`Exposure` int    NULL , 
`ExposureInuAs` int    NULL , 
`ExposureTime` int    NULL , 
`FocalSpots` text    NULL , 
`Grid` text    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`ImagePositionPatient` text    NULL , 
`ImageType` text    NULL , 
`ImagerPixelSpacing` text    NULL , 
`IntensifierSize` decimal(38,19)    NULL , 
`KVP` decimal(38,19)    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`Manufacturer` varchar(64)    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`PixelAspectRatio` text    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`PixelSpacing` text    NULL , 
`PixelSpacingCalibrationDescription` varchar(64)    NULL , 
`PixelSpacingCalibrationType` varchar(16)    NULL , 
`PlanarConfiguration` smallint    NULL , 
`PositionerMotion` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RadiationMode` varchar(16)    NULL , 
`RadiationSetting` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`Rows` smallint    NULL , 
`SamplesPerPixel` smallint    NULL , 
`ScanOptions` text    NULL , 
`SoftwareVersions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`TypeOfFilters` text    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`XRayTubeCurrentInuA` decimal(38,19)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`PatientID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
CONSTRAINT PK_XA_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`XA_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`Modality` varchar(16)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`SeriesTime` time    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_XA_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`XA_StudyTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`AccessionNumber` varchar(16)    NULL , 
`ModalitiesInStudy` text    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientAge` varchar(4)    NULL , 
`PatientBirthDate` datetime    NULL , 
`PatientID` varchar(64)    NULL , 
`PatientSex` varchar(16)    NULL , 
`StudyDate` datetime    NULL , 
`StudyDescription` varchar(64)    NULL , 
`StudyTime` time    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_XA_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`CR_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_CR_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`CR_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_CR_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`CR_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_CR_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`CT_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`SliceLocation` decimal(38,19)    NULL , 
`SliceThickness` decimal(38,19)    NULL , 
`SpacingBetweenSlices` decimal(38,19)    NULL , 
`SpiralPitchFactor` decimal(38,19)    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`ContrastBolusRoute` varchar(64)    NULL , 
`ContrastBolusAgent` varchar(64)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`FieldOfViewDimensions` text    NULL , 
`FieldOfViewDimensionsInFloat` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`hic_validFrom` datetime    NOT NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_CT_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`CT_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NOT NULL , 
CONSTRAINT PK_CT_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`CT_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`PatientBirthDate` datetime    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NOT NULL , 
CONSTRAINT PK_CT_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`DX_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_DX_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`DX_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_DX_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`DX_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_DX_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`MR_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`SliceLocation` decimal(38,19)    NULL , 
`SliceThickness` decimal(38,19)    NULL , 
`SpacingBetweenSlices` decimal(38,19)    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`ContrastBolusRoute` varchar(64)    NULL , 
`ContrastBolusAgent` varchar(64)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`ImageOrientationPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`FieldOfViewDimensions` text    NULL , 
`FieldOfViewDimensionsInFloat` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`EchoTime` decimal(38,19)    NULL , 
`EchoNumbers` text    NULL , 
`EchoTrainLength` int    NULL , 
`InversionTime` decimal(38,19)    NULL , 
`RepetitionTime` decimal(38,19)    NULL , 
`NumberOfPhaseEncodingSteps` int    NULL , 
`FlipAngle` decimal(38,19)    NULL , 
`VariableFlipAngleFlag` varchar(16)    NULL , 
`SequenceName` varchar(16)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`hic_validFrom` datetime    NOT NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_MR_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`MR_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`MRAcquisitionType` varchar(16)    NULL , 
`AngioFlag` varchar(16)    NULL , 
`MagneticFieldStrength` decimal(38,19)    NULL , 
`TransmitCoilName` varchar(16)    NULL , 
`PatientPosition` varchar(16)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NOT NULL , 
CONSTRAINT PK_MR_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`MR_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`PatientBirthDate` datetime    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NOT NULL , 
CONSTRAINT PK_MR_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`NM_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`SliceLocation` decimal(38,19)    NULL , 
`SliceThickness` decimal(38,19)    NULL , 
`SpacingBetweenSlices` decimal(38,19)    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`FieldOfViewDimensions` text    NULL , 
`ActualFrameDuration` int    NULL , 
`FieldOfViewDimensionsInFloat` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`DetectorInformation_RadialPosition` text    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_NM_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`NM_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`NumberOfSlices` smallint    NULL , 
`EnergyWindowRange_EnergyWindowLowerLimit` varchar(64)    NULL , 
`EnergyWindowRange_EnergyWindowUpperLimit` varchar(64)    NULL , 
`RadInfo_Radiopharmaceutica` varchar(64)    NULL , 
`RadInfo_RadiopharmaceuticalVolume` varchar(64)    NULL , 
`RadInfo_RadCode_CodeValue` text    NULL , 
`RadInfo_RadCode_CodeMeaning` varchar(64)    NULL , 
`RadInfo_RadionuclideTotalDose` varchar(64)    NULL , 
`NumberOfDetectors` smallint    NULL , 
`DetectorInformation_CollimatorGridName` text    NULL , 
`DetectorInformation_CollimatorType` text    NULL , 
`DetectorInformation_FieldOfViewShape` varchar(64)    NULL , 
`DetectorInformation_FieldOfViewDimensions` text    NULL , 
`DetectorInformation_ZoomFactor` varchar(100)    NULL , 
`RotationInformation_ScanArc` varchar(64)    NULL , 
`RotationInformation_AngularStep` varchar(64)    NULL , 
`RotationInformation_NumberOfFramesInRotation` smallint    NULL , 
`TypeOfDetectorMotion` varchar(16)    NULL , 
`RandomsCorrectionMethod` varchar(16)    NULL , 
`AttenuationCorrectionMethod` varchar(64)    NULL , 
`DecayCorrection` varchar(16)    NULL , 
`ReconstructionMethod` varchar(64)    NULL , 
`ScatterCorrectionMethod` varchar(64)    NULL , 
`DateOfLastCalibration` text    NULL , 
`TimeOfLastCalibration` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_NM_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`NM_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_NM_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`PT_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`SliceLocation` decimal(38,19)    NULL , 
`SliceThickness` decimal(38,19)    NULL , 
`SpacingBetweenSlices` decimal(38,19)    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`FieldOfViewDimensions` text    NULL , 
`ActualFrameDuration` int    NULL , 
`FieldOfViewDimensionsInFloat` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_PT_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`PT_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`NumberOfSlices` smallint    NULL , 
`EnergyWindowRange_EnergyWindowLowerLimit` decimal(38,19)    NULL , 
`EnergyWindowRange_EnergyWindowUpperLimit` decimal(38,19)    NULL , 
`RadInfo_Radiopharmaceutical` varchar(64)    NULL , 
`RadInfo_RadiopharmaceuticalVolume` decimal(38,19)    NULL , 
`RadInfo_RadCode_CodeValue` varchar(16)    NULL , 
`RadInfo_RadCode_CodeMeaning` varchar(64)    NULL , 
`RadInfo_RadionuclideTotalDose` decimal(38,19)    NULL , 
`RandomsCorrectionMethod` varchar(16)    NULL , 
`AttenuationCorrectionMethod` varchar(64)    NULL , 
`DecayCorrection` varchar(16)    NULL , 
`ReconstructionMethod` varchar(64)    NULL , 
`ScatterCorrectionMethod` varchar(64)    NULL , 
`DateOfLastCalibration` text    NULL , 
`TimeOfLastCalibration` text    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_PT_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`PT_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_PT_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`PX_ImageTable`( 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`BurnedInAnnotation` varchar(16)    NULL , 
`RelativeFileArchiveURI` varchar(512)    NULL , 
`MessageGuid` text    NULL , 
`KVP` decimal(38,19)    NULL , 
`ExposureTime` int    NULL , 
`Exposure` int    NULL , 
`ImageType` text    NULL , 
`ManufacturerModelName` varchar(64)    NULL , 
`Manufacturer` varchar(64)    NULL , 
`SoftwareVersions` text    NULL , 
`XRayTubeCurrent` int    NULL , 
`PhotometricInterpretation` varchar(16)    NULL , 
`AcquisitionNumber` int    NULL , 
`AcquisitionDate` datetime    NULL , 
`AcquisitionTime` time    NULL , 
`ImagePositionPatient` text    NULL , 
`PixelSpacing` text    NULL , 
`DerivationDescription` text    NULL , 
`LossyImageCompression` varchar(16)    NULL , 
`LossyImageCompressionMethod` text    NULL , 
`LossyImageCompressionRatio` text    NULL , 
`LossyImageCompressionRetired` varchar(16)    NULL , 
`ScanOptions` text    NULL , 
`SpatialResolution` decimal(38,19)    NULL , 
`DistanceSourceToDetector` decimal(38,19)    NULL , 
`ExposureInuAs` int    NULL , 
`DistanceSourceToPatient` decimal(38,19)    NULL , 
`EstimatedRadiographicMagnificationFactor` decimal(38,19)    NULL , 
`ImageAndFluoroscopyAreaDoseProduct` decimal(38,19)    NULL , 
`Grid` text    NULL , 
`Rows` smallint    NULL , 
`Columns` smallint    NULL , 
`LongitudinalTemporalInformationModified` varchar(16)    NULL , 
`PixelIntensityRelationshipSign` smallint    NULL , 
`WindowCenter` text    NULL , 
`WindowWidth` text    NULL , 
`RescaleIntercept` decimal(38,19)    NULL , 
`RescaleSlope` decimal(38,19)    NULL , 
`RescaleType` varchar(64)    NULL , 
`CollimatorShape` text    NULL , 
`CollimatorLeftVerticalEdge` int    NULL , 
`CollimatorRightVerticalEdge` int    NULL , 
`CollimatorUpperHorizontalEdge` int    NULL , 
`CollimatorLowerHorizontalEdge` int    NULL , 
`ViewPosition` varchar(16)    NULL , 
`DetectorTemperature` decimal(38,19)    NULL , 
`DetectorType` varchar(16)    NULL , 
`DetectorMode` text    NULL , 
`DetectorID` varchar(16)    NULL , 
`PositionerType` varchar(16)    NULL , 
`RelativeXRayExposure` int    NULL , 
`AcquisitionDeviceProcessingDescription` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`DicomFileSize` bigint    NULL , 
`PatientID` varchar(64)    NULL , 
CONSTRAINT PK_PX_ImageTable PRIMARY KEY (`SOPInstanceUID`)); 
  
  

CREATE TABLE `smi`.`PX_SeriesTable`( 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`SeriesInstanceUID` varchar(64)    NOT NULL , 
`Modality` varchar(16)    NULL , 
`InstitutionName` varchar(64)    NULL , 
`ProtocolName` varchar(64)    NULL , 
`ProcedureCodeSequence_CodeValue` varchar(100)    NULL , 
`PerformedProcedureStepDescription` varchar(64)    NULL , 
`SeriesDescription` varchar(64)    NULL , 
`SeriesDate` datetime    NULL , 
`SeriesTime` time    NULL , 
`BodyPartExamined` varchar(16)    NULL , 
`DeviceSerialNumber` varchar(64)    NULL , 
`SeriesNumber` int    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_PX_SeriesTable PRIMARY KEY (`SeriesInstanceUID`)) 
  
  

CREATE TABLE `smi`.`PX_StudyTable`( 
`PatientID` varchar(64)    NOT NULL , 
`StudyInstanceUID` varchar(64)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` text    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(16)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_PX_StudyTable PRIMARY KEY (`StudyInstanceUID`)) 
  
  

CREATE TABLE `smi`.`SOME_StudyTable`( 
`PatientID` varchar(64)    NULL , 
`SOPInstanceUID` varchar(64)    NOT NULL , 
`RelativeFileArchiveURI` varchar(512)    NOT NULL , 
`StudyDate` datetime    NULL , 
`StudyTime` time    NULL , 
`ModalitiesInStudy` varchar(30)    NULL , 
`Modality` varchar(16)    NULL , 
`StudyDescription` varchar(64)    NULL , 
`AccessionNumber` varchar(26)    NULL , 
`PatientSex` varchar(16)    NULL , 
`PatientAge` varchar(4)    NULL , 
`NumberOfStudyRelatedInstances` int    NULL , 
`PatientBirthDate` datetime    NULL , 
`DicomFileSize` bigint    NULL , 
`SeriesDescription` varchar(120)    NULL , 
`StudyInstanceUID` varchar(64)    NULL , 
`SeriesInstanceUID` varchar(64)    NULL , 
`hic_dataLoadRunID` int    NULL , 
`hic_validFrom` datetime    NULL , 
CONSTRAINT PK_SOME_StudyTable PRIMARY KEY (`SOPInstanceUID`));  
GRANT ALL ON smi.* TO ‘smi’@’localhost’ IDENTIFIED BY ‘SmiSqlPassword’; 

CREATE DATABASE smi_isolation; 
GRANT ALL ON smi_isolation.* TO ‘smi’@’localhost’ IDENTIFIED BY ‘SmiSqlPassword’; 
