---
trigger:
    branches:
        include:
            - "*"
    tags:
        include:
            - "*"

jobs:
    - template: jobs/tests.tmpl.yml
      parameters:
          vmImage: ubuntu-18.04
          os: linux
    - template: jobs/package.tmpl.yml
      parameters:
          vmImage: ubuntu-18.04
          os: linux
