---
trigger:
    branches:
        include:
            - "*"
    tags:
        include:
            - "*"

jobs:
    - template: jobs/tests.tmpl.yml
      parameters:
          vmImage: windows-2019
          os: win
    - template: jobs/package.tmpl.yml
      parameters:
          vmImage: windows-2019
          os: win
